worker_processes auto;
user www-data;

events {
	worker_connections 1024;
}

http {

	include mime.types;

	server {
		# root /var/www/html;
		root /var/www/web;
		# index index.nginx-debian.html;

		autoindex on;

		location =  /about {
			return 200 'About me';
		}

		location /readme {
			try_files /readme.html =404;	
		}
	}
}
