worker_processes auto;
user www-data;

events {
	worker_connections 1024;
}

sendfile on;

http {

	include mime.types;

	error_page 404 /404.html;

	server {
		# root /var/www/html;
		root /var/www/web;
		# index index.nginx-debian.html;

		autoindex on;

		location =  /about {
			return 200 'About me';
		}

		location /readme {
			try_files /readme.html =404;	
		}

		location /contact/ {
			index /contact.html;
		}

		# location / {
		# 	error_page 404 /404.html;
		# }
	}
}
